version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    govet:
      enable:
        - shadow
    lll:
      line-length: 140
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - goconst
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - gocritic
        path: internal/tui/dashboard/model\.go
        text: hugeParam
      - linters:
          - gocritic
        path: internal/tui/dashboard/modal\.go
        text: hugeParam
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/TechnicallyShaun/crAIzy
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
