linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/TechnicallyShaun/crAIzy
  golint:
    min-confidence: 0
  govet:
    enable:
      - shadow
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  misspell:
    locale: US

linters:
  disable:
    - typecheck
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
        - gocritic
        - unparam
    - linters:
        - typecheck
      text: "undefined: yaml"
    # Bubble Tea models must use value receivers per the tea.Model interface
    - path: internal/tui/
      linters:
        - gocritic
      text: "hugeParam"
    # Bubble Tea Update functions tend to have high cyclomatic complexity
    - path: internal/tui/dashboard\.go
      linters:
        - gocyclo
    # Git client uses external input for git commands, which is expected
    - path: internal/infra/git_client\.go
      linters:
        - gosec
      text: "G204"
    # Config file permissions are expected to be 0644
    - path: cmd/craizy/init\.go
      linters:
        - gosec
      text: "G306"
    # Common key strings in TUI are repeated but readable inline
    - path: internal/tui/
      linters:
        - goconst
      text: "enter|esc|left|right|Loading"
    # singleCaseSwitch is fine for tea.Msg type switches - clarity over brevity
    - path: internal/tui/
      linters:
        - gocritic
      text: "singleCaseSwitch"

run:
  timeout: 5m
  tests: true
